name: Python application

on:
  workflow_dispatch:
  # schedule:
  # - cron:  '0 21 * * *'

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install system dependencies for Kaleido
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6
    - name: Install font
      run: sudo apt install fonts-ipafont
    - name: Run script
      run: |
        python main.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    - name: git setting
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit files
      run: |
        git add -N .
        if ! git diff --exit-code --quiet
        then
          git add .
          git commit -m "ファイル更新" -a
          git push
        fi
